=== petarMarinovic/OR-labos/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "localhost:63342/schema.json",
  "title": "OR muzički albumi",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Naziv": {
        "type": "string"
      },
      "Žanr": {
        "type": "string"
      },
      "Format": {
        "type": "string"
      },
      "Godina": {
        "type": "number"
      },
      "Pjesme": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "Redni_broj": {
              "type": "number"
            },
            "Naziv_pjesme": {
              "type": "string"
            },
            "Trajanje_minute": {
              "type": "number"
            }
          },
          "required": [
            "Redni_broj",
            "Naziv_pjesme",
            "Trajanje_minute"
          ]
        }
      },
      "Zemlja": {
        "type": "string"
      },
      "Izvođač": {
        "type": "string"
      },
      "Broj_pjesama": {
        "type": "number"
      },
      "Trajanje_min": {
        "type": "number"
      },
      "Platinum_status": {
        "type": "boolean"
      },
      "Izdavačka_kuća": {
        "type": "string"
      }
    },
    "required": [
      "Naziv",
      "Žanr",
      "Format",
      "Godina",
      "Pjesme",
      "Zemlja",
      "Izvođač",
      "Broj_pjesama",
      "Trajanje_min",
      "Platinum_status",
      "Izdavačka_kuća"
    ]
  }
}

=== petarMarinovic/OR-labos/muzicki_albumi.json
[{"Naziv": "The Dark Side of the Moon", "Žanr": "Progressive Rock", "Format": "Vinyl", "Godina": 1973, "Pjesme": [{"Redni_broj": 1, "Naziv_pjesme": "Speak to Me", "Trajanje_minute": 1.50}, {"Redni_broj": 2, "Naziv_pjesme": "Breathe", "Trajanje_minute": 2.72}, {"Redni_broj": 3, "Naziv_pjesme": "On the Run", "Trajanje_minute": 3.60}, {"Redni_broj": 4, "Naziv_pjesme": "Time", "Trajanje_minute": 6.88}, {"Redni_broj": 5, "Naziv_pjesme": "The Great Gig in the Sky", "Trajanje_minute": 4.72}, {"Redni_broj": 6, "Naziv_pjesme": "Money", "Trajanje_minute": 6.50}, {"Redni_broj": 7, "Naziv_pjesme": "Us and Them", "Trajanje_minute": 7.82}, {"Redni_broj": 8, "Naziv_pjesme": "Any Colour You Like", "Trajanje_minute": 3.45}, {"Redni_broj": 9, "Naziv_pjesme": "Brain Damage", "Trajanje_minute": 3.78}, {"Redni_broj": 10, "Naziv_pjesme": "Eclipse", "Trajanje_minute": 2.05}], "Zemlja": "Ujedinjeno Kraljevstvo", "Izvođač": "Pink Floyd", "Broj_pjesama": 10, "Trajanje_min": 43, "Platinum_status": true, "Izdavačka_kuća": "Harvest Records"}, {"Naziv": "Thriller", "Žanr": "Pop", "Format": "CD", "Godina": 1982, "Pjesme": [{"Redni_broj": 1, "Naziv_pjesme": "Wanna Be Startin Somethin", "Trajanje_minute": 6.05}, {"Redni_broj": 2, "Naziv_pjesme": "Baby Be Mine", "Trajanje_minute": 4.33}, {"Redni_broj": 3, "Naziv_pjesme": "The Girl Is Mine", "Trajanje_minute": 3.70}, {"Redni_broj": 4, "Naziv_pjesme": "Thriller", "Trajanje_minute": 5.95}, {"Redni_broj": 5, "Naziv_pjesme": "Beat It", "Trajanje_minute": 4.30}, {"Redni_broj": 6, "Naziv_pjesme": "Billie Jean", "Trajanje_minute": 4.92}, {"Redni_broj": 7, "Naziv_pjesme": "Human Nature", "Trajanje_minute": 4.10}, {"Redni_broj": 8, "Naziv_pjesme": "P.Y.T.", "Trajanje_minute": 3.97}, {"Redni_broj": 9, "Naziv_pjesme": "The Lady in My Life", "Trajanje_minute": 5.00}], "Zemlja": "Sjedinjene Američke Države", "Izvođač": "Michael Jackson", "Broj_pjesama": 9, "Trajanje_min": 42, "Platinum_status": true, "Izdavačka_kuća": "Epic Records"}, {"Naziv": "Back in Black", "Žanr": "Hard Rock", "Format": "Vinyl", "Godina": 1980, "Pjesme": [{"Redni_broj": 1, "Naziv_pjesme": "Hells Bells", "Trajanje_minute": 5.20}, {"Redni_broj": 2, "Naziv_pjesme": "Shoot to Thrill", "Trajanje_minute": 5.28}, {"Redni_broj": 3, "Naziv_pjesme": "What Do You Do for Money Honey", "Trajanje_minute": 3.55}, {"Redni_broj": 4, "Naziv_pjesme": "Given the Dog a Bone", "Trajanje_minute": 3.48}, {"Redni_broj": 5, "Naziv_pjesme": "Let Me Put My Love into You", "Trajanje_minute": 4.23}, {"Redni_broj": 6, "Naziv_pjesme": "Back in Black", "Trajanje_minute": 4.25}, {"Redni_broj": 7, "Naziv_pjesme": "You Shook Me All Night Long", "Trajanje_minute": 3.50}, {"Redni_broj": 8, "Naziv_pjesme": "Have a Drink on Me", "Trajanje_minute": 3.98}, {"Redni_broj": 9, "Naziv_pjesme": "Shake a Leg", "Trajanje_minute": 4.05}, {"Redni_broj": 10, "Naziv_pjesme": "Rock and Roll Ain't Noise Pollution", "Trajanje_minute": 4.25}], "Zemlja": "Australija", "Izvođač": "AC/DC", "Broj_pjesama": 10, "Trajanje_min": 42, "Platinum_status": true, "Izdavačka_kuća": "Atlantic Records"}, {"Naziv": "Abbey Road", "Žanr": "Rock", "Format": "Vinyl", "Godina": 1969, "Pjesme": [{"Redni_broj": 1, "Naziv_pjesme": "Come Together", "Trajanje_minute": 4.33}, {"Redni_broj": 2, "Naziv_pjesme": "Something", "Trajanje_minute": 3.03}, {"Redni_broj": 3, "Naziv_pjesme": "Maxwell s Silver Hammer", "Trajanje_minute": 3.45}, {"Redni_broj": 4, "Naziv_pjesme": "Oh! Darling", "Trajanje_minute": 3.47}, {"Redni_broj": 5, "Naziv_pjesme": "Octopus's Garden", "Trajanje_minute": 2.85}, {"Redni_broj": 6, "Naziv_pjesme": "I Want You", "Trajanje_minute": 7.80}, {"Redni_broj": 7, "Naziv_pjesme": "Here Comes the Sun", "Trajanje_minute": 3.08}, {"Redni_broj": 8, "Naziv_pjesme": "Because", "Trajanje_minute": 2.70}, {"Redni_broj": 9, "Naziv_pjesme": "You Never Give Me Your Money", "Trajanje_minute": 4.03}, {"Redni_broj": 10, "Naziv_pjesme": "Sun King", "Trajanje_minute": 2.45}, {"Redni_broj": 11, "Naziv_pjesme": "Mean Mr. Mustard", "Trajanje_minute": 1.10}, {"Redni_broj": 12, "Naziv_pjesme": "Polythene Pam", "Trajanje_minute": 1.22}, {"Redni_broj": 13, "Naziv_pjesme": "She Came in Through the Bathroom Window", "Trajanje_minute": 1.97}, {"Redni_broj": 14, "Naziv_pjesme": "Golden Slumbers", "Trajanje_minute": 1.60}, {"Redni_broj": 15, "Naziv_pjesme": "Carry That Weight", "Trajanje_minute": 1.63}, {"Redni_broj": 16, "Naziv_pjesme": "The End", "Trajanje_minute": 2.33}, {"Redni_broj": 17, "Naziv_pjesme": "Her Majesty", "Trajanje_minute": 0.38}], "Zemlja": "Ujedinjeno Kraljevstvo", "Izvođač": "The Beatles", "Broj_pjesama": 17, "Trajanje_min": 47, "Platinum_status": true, "Izdavačka_kuća": "Apple Records"}, {"Naziv": "Rumours", "Žanr": "Rock", "Format": "Vinyl", "Godina": 1977, "Pjesme": [{"Redni_broj": 1, "Naziv_pjesme": "Second Hand News", "Trajanje_minute": 2.72}, {"Redni_broj": 2, "Naziv_pjesme": "Dreams", "Trajanje_minute": 4.25}, {"Redni_broj": 3, "Naziv_pjesme": "Never Going Back Again", "Trajanje_minute": 2.10}, {"Redni_broj": 4, "Naziv_pjesme": "Don't Stop", "Trajanje_minute": 3.20}, {"Redni_broj": 5, "Naziv_pjesme": "Go Your Own Way", "Trajanje_minute": 3.65}, {"Redni_broj": 6, "Naziv_pjesme": "Songbird", "Trajanje_minute": 3.35}, {"Redni_broj": 7, "Naziv_pjesme": "The Chain", "Trajanje_minute": 4.50}, {"Redni_broj": 8, "Naziv_pjesme": "You Make Loving Fun", "Trajanje_minute": 3.58}, {"Redni_broj": 9, "Naziv_pjesme": "I Don't Want to Know", "Trajanje_minute": 3.20}, {"Redni_broj": 10, "Naziv_pjesme": "Oh Daddy", "Trajanje_minute": 3.93}, {"Redni_broj": 11, "Naziv_pjesme": "Gold Dust Woman", "Trajanje_minute": 4.83}], "Zemlja": "Sjedinjene Američke Države", "Izvođač": "Fleetwood Mac", "Broj_pjesama": 11, "Trajanje_min": 40, "Platinum_status": true, "Izdavačka_kuća": "Warner Bros"}, {"Naziv": "Nevermind", "Žanr": "Grunge", "Format": "CD", "Godina": 1991, "Pjesme": [{"Redni_broj": 1, "Naziv_pjesme": "Smells Like Teen Spirit", "Trajanje_minute": 5.02}, {"Redni_broj": 2, "Naziv_pjesme": "In Bloom", "Trajanje_minute": 4.23}, {"Redni_broj": 3, "Naziv_pjesme": "Come as You Are", "Trajanje_minute": 3.72}, {"Redni_broj": 4, "Naziv_pjesme": "Breed", "Trajanje_minute": 3.05}, {"Redni_broj": 5, "Naziv_pjesme": "Lithium", "Trajanje_minute": 4.28}, {"Redni_broj": 6, "Naziv_pjesme": "Polly", "Trajanje_minute": 2.95}, {"Redni_broj": 7, "Naziv_pjesme": "Territorial Pissings", "Trajanje_minute": 2.38}, {"Redni_broj": 8, "Naziv_pjesme": "Drain You", "Trajanje_minute": 3.72}, {"Redni_broj": 9, "Naziv_pjesme": "Lounge Act", "Trajanje_minute": 2.62}, {"Redni_broj": 10, "Naziv_pjesme": "Stay Away", "Trajanje_minute": 3.55}, {"Redni_broj": 11, "Naziv_pjesme": "On a Plain", "Trajanje_minute": 3.27}, {"Redni_broj": 12, "Naziv_pjesme": "Something in the Way", "Trajanje_minute": 3.93}], "Zemlja": "Sjedinjene Američke Države", "Izvođač": "Nirvana", "Broj_pjesama": 12, "Trajanje_min": 43, "Platinum_status": true, "Izdavačka_kuća": "DGC Records"}, {"Naziv": "Led Zeppelin IV", "Žanr": "Hard rock", "Format": "Vinyl", "Godina": 1971, "Pjesme": [{"Redni_broj": 1, "Naziv_pjesme": "Black Dog", "Trajanje_minute": 4.97}, {"Redni_broj": 2, "Naziv_pjesme": "Rock and Roll", "Trajanje_minute": 3.67}, {"Redni_broj": 3, "Naziv_pjesme": "The Battle of Evermore", "Trajanje_minute": 5.85}, {"Redni_broj": 4, "Naziv_pjesme": "Stairway to Heaven", "Trajanje_minute": 8.03}, {"Redni_broj": 5, "Naziv_pjesme": "Misty Mountain Hop", "Trajanje_minute": 4.63}, {"Redni_broj": 6, "Naziv_pjesme": "Four Sticks", "Trajanje_minute": 4.73}, {"Redni_broj": 7, "Naziv_pjesme": "Going to California", "Trajanje_minute": 3.52}, {"Redni_broj": 8, "Naziv_pjesme": "When the Levee Breaks", "Trajanje_minute": 7.08}], "Zemlja": "Ujedinjeno Kraljevstvo", "Izvođač": "Led Zeppelin", "Broj_pjesama": 8, "Trajanje_min": 42, "Platinum_status": true, "Izdavačka_kuća": "Atlantic Records"}, {"Naziv": "The Wall", "Žanr": "Progressive rock", "Format": "Vinyl", "Godina": 1979, "Pjesme": [{"Redni_broj": 1, "Naziv_pjesme": "In the Flesh?", "Trajanje_minute": 3.33}, {"Redni_broj": 2, "Naziv_pjesme": "The Thin Ice", "Trajanje_minute": 2.50}, {"Redni_broj": 3, "Naziv_pjesme": "Another Brick in the Wall (Part 1)", "Trajanje_minute": 3.17}, {"Redni_broj": 4, "Naziv_pjesme": "The Happiest Days of Our Lives", "Trajanje_minute": 1.80}, {"Redni_broj": 5, "Naziv_pjesme": "Another Brick in the Wall (Part 2)", "Trajanje_minute": 3.97}, {"Redni_broj": 6, "Naziv_pjesme": "Mother", "Trajanje_minute": 5.57}, {"Redni_broj": 7, "Naziv_pjesme": "Goodbye Blue Sky", "Trajanje_minute": 2.75}, {"Redni_broj": 8, "Naziv_pjesme": "Empty Spaces", "Trajanje_minute": 2.17}, {"Redni_broj": 9, "Naziv_pjesme": "Young Lust", "Trajanje_minute": 3.42}, {"Redni_broj": 10, "Naziv_pjesme": "One of My Turns", "Trajanje_minute": 3.70}, {"Redni_broj": 11, "Naziv_pjesme": "Don't Leave Me Now", "Trajanje_minute": 4.25}, {"Redni_broj": 12, "Naziv_pjesme": "Another Brick in the Wall (Part 3)", "Trajanje_minute": 1.28}, {"Redni_broj": 13, "Naziv_pjesme": "Goodbye Cruel World", "Trajanje_minute": 1.22}, {"Redni_broj": 14, "Naziv_pjesme": "Hey You", "Trajanje_minute": 4.67}, {"Redni_broj": 15, "Naziv_pjesme": "Is There Anybody Out There?", "Trajanje_minute": 2.60}, {"Redni_broj": 16, "Naziv_pjesme": "Nobody Home", "Trajanje_minute": 3.42}, {"Redni_broj": 17, "Naziv_pjesme": "Vera", "Trajanje_minute": 1.58}, {"Redni_broj": 18, "Naziv_pjesme": "Bring the Boys Back Home", "Trajanje_minute": 1.35}, {"Redni_broj": 19, "Naziv_pjesme": "Comfortably Numb", "Trajanje_minute": 6.37}, {"Redni_broj": 20, "Naziv_pjesme": "The Show Must Go On", "Trajanje_minute": 1.58}, {"Redni_broj": 21, "Naziv_pjesme": "In the Flesh", "Trajanje_minute": 4.30}, {"Redni_broj": 22, "Naziv_pjesme": "Run Like Hell", "Trajanje_minute": 4.33}, {"Redni_broj": 23, "Naziv_pjesme": "Waiting for the Worms", "Trajanje_minute": 4.00}, {"Redni_broj": 24, "Naziv_pjesme": "Stop", "Trajanje_minute": 0.50}, {"Redni_broj": 25, "Naziv_pjesme": "The Trial", "Trajanje_minute": 5.22}, {"Redni_broj": 26, "Naziv_pje
